#!/bin/env bash

# Pre remove script for dpkg/apt
case "${1}" in
    remove|purge|upgrade)
        if systemctl is-active --quiet btrfs-snapshots-manager.timer ; then
            systemctl disable --now btrfs-snapshots-manager.timer
            rm -f /usr/lib/systemd/system/btrfs-snapshots-manager.timer
        fi
    ;;
    *)
        echo "prerm called with unknown argument ${1}" >&2
        exit 0
    ;;
esac
