#!/bin/env bash

# btrfs-snapshot copyright (c) 2024 by <mschaecher78@gmail.com> Michael L. Schaecher - MIT License

# This script creates a btrfs snapshot of the root filesystem and deletes old snapshots helping
# keep data usage manageable.

# shellcheck disable=SC2317
function cleanUp () {

    mountedTmp="$(mount | grep 'on /tmp/' | awk '{print $1}')"
    umount "${mountedTmp}" || { sysLog "Failed to unmount ${mountedTmp}" ; exit 1 ; }
    rm -rf "${_snapshotsDir}" || { sysLog "Failed to remove temporary directory ${_snapshotsDir}" ; exit 1 ; }

    sysLog "Temporary directory ${_snapshotsDir} removed successfully" ; exit 0

}

function rootRequired () { (( $(id -u) == 0 )) || { sysLog "This script must be run as root" ; exit 1 ; } ; }

# Log all output to syslog
function sysLog () { logger -t btrfs-snapshot "$@" ; }

function deleteSnapshot () {

    btrfs su delete "${1}" || { sysLog "Failed to delete snapshot ${1}" ; exit 1 ; }
    sysLog "Snapshot ${1} deleted successfully"

}

function deleteOldestSnapshot () {

    local oldSnapshots snapshotList targetDir

    targetDir="${_snapshotsDir}}"

    # Delete snapshots exceeding the total to keep
    while true ; do

        oldSnapshots="$(btrfs su list -o --sort=ogen "${targetDir}" | awk -F'/' 'NR==1 {print $2}')"

        # Using the find command is better then ls, however the one less snapshot is kept.
        # Need to add 1 to the TOTAL_KEEP variable to keep the correct number of snapshots.
        count=$((_totalCount + 1))

        snapshotList="$(find "${targetDir}" -maxdepth 1 -type d | wc -l)"

        if test "${snapshotList}" -gt "${count}" ; then
            deleteSnapshot "${targetDir}/${oldSnapshots}"
        else
            break
        fi

    done

}

function deleteSnapshotList () {

    _deleteHelpInfo="$(cat << EOF
${_versionInfo}

Usage: ${_appName} delete <flags> arg...

Options:
    delete                     Delete a snapshot based on configured settings.

Flags:
    -o, --oldest               Delete the oldest snapshot in the snapshot directory.
    -l, --list                 List all available snapshots in the snapshot directory.
    -y, --yes                  Skip the confirmation prompt before deleting the snapshot.
    -h, --help                 Show help information for deleting a snapshot.

${_licenseInfo}
EOF
)"

    local snapshotsList snapshotsName targetDir

    shift

    snapshotsList=() ; targetDir="${_snapshotsDir}"

    case "${1}" in
        -h|--help                 ) echo "${_deleteHelpInfo}"                 ; exit 0 ;;
    esac

    # Check if the script is run with root privileges
    rootRequired

    while true ; do case "${1}" in
        -o|--oldest               ) deleteOldestSnapshot                      ; break  ;;
        -y|--yes                  ) confirm="yes"                             ; shift  ;;
        -l|--list                 )
            while IFS= read -r -d $'\0' snap; do
                snapshotsName=$(basename "$snap") && snapshotsList+=("$snapshotsName")
            done < <(find "$targetDir" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

            echo "Available snapshots:"
            echo ""

            select snap in "${snapshotsList[@]}" ; do
                test -z "${snap}" || { selectedSnapshot="$snap" ; break ; }
            done
            shift
        ;;
        *) break ;;
    esac ; done

    if test "${confirm}" != "yes" ; then
        # Prompt for confirmation before deleting the snapshot
        read -rp "Are you sure you want to delete the snapshot ${selectedSnapshot} in ${targetDir}? [y/N] " choice
        case "${choice}" in
            [yY][eE][sS]|[yY]       ) ;;
            *                       ) sysLog "Snapshot deletion cancelled"    ; exit 0 ;;
        esac
    fi

    # Verify that the target directory exists
    test -d "${targetDir}" || { sysLog "Snapshot target directory ${targetDir} does not exist" ; exit 1 ; }

    deleteSnapshot "${targetDir}/${selectedSnapshot}"

}

function takeSnapshot () {

_createHelpInfo="$(cat << EOF
${_versionInfo}

Usage: ${_appName} create <flags> arg...

Options:
    create                      Create a new snapshot based on configured settings.

Flag:
    -r, --read-only             Create a read-only snapshot: This will not allow any changes to the snapshot
                                after creation.
    -y, --yes                   Skip the confirmation prompt before creating the snapshot.
    -s, --source <source>       Specify the source for the snapshot: [\`root\`, \`home\`, or \`logs\`].
    -t, --target <target>       Specify the target location for the snapshot: [Default is \`/.snapshots\`].
    -w, --writeable             Convert a given snapshot to a writeable state: This allows changes to be made
                                to the snapshot after creation.
    -h, --help                  Show help information for creating a snapshot.

${_licenseInfo}
EOF
)"

    shift

    case "${1}" in
        -h|--help                 ) echo "${_createHelpInfo}"                 ; exit 0 ;;
    esac

    # Check if the script is run with root privileges
    rootRequired

    local snapshotOptions confirm sourceDir targetDir snapshotOut

    snapshotOptions="su snapshot" ; targetDir="${_snapshotsDir}" ; sourceDir="/"

    while true ; do case "${1}" in
        -r|--read-only              ) snapshotOptions="${snapshotOptions} -r" ; shift  ;;
        -y|--yes                    ) confirm="yes"                           ; shift  ;;
        -s|--source                 )
            # Set the source directory from which to create the snapshot.
            case "${2}" in
                root                ) sourceDir="/";;
                home                ) sourceDir="/home";;
                logs                ) sourceDir="/var/log";;
                *                   ) sysLog "Invalid source directory: ${2}" ; exit 1 ;;
            esac
            shift 2
        ;;
        -t|--target                 )
            # Check if a flag is next instead of a directory
            if [[ "${2}" == -* ]] ; then targetDir="${SNAPSHOT_DIR}" ; else targetDir="${2}" ; shift 2 ; fi
        ;;
        -w|--writeable              )
            # Verify that the target directory exists
            test -d "${2}" || { sysLog "Snapshot target directory ${2} does not exist" ; exit 1 ; }

            btrfs property set "${2}" ro false || {
                sysLog "Failed to set writeable property on ${2}" ; exit 1
            }

            # Don't want to continue with the snapshot with this flag for now.
            sysLog "${2} set to writeable, skipping snapshot creation" ; exit 0
        ;;
        *) break ;;
    esac ; done

    # Verify that the target directory exists
    test -d "${targetDir}" || { sysLog "Snapshot target directory ${targetDir} does not exist" ; exit 1 ; }

    if test "$confirm" != "yes" ; then
        # Prompt for confirmation before creating the snapshot
        read -rp "Are you sure you want to create a snapshot of ${sourceDir} in ${targetDir}? [y/N] " choice
        case "${choice}" in
            [yY][eE][sS]|[yY]       ) ;;
            *                       ) sysLog "Snapshot creation cancelled"    ; exit 0 ;;
        esac
    fi

    snapshotOut="${_distroName}_${_snapshotType}_$(date +%Y%m%d+%H%M)"

    # shellcheck disable=SC2086
    btrfs ${snapshotOptions} ${sourceDir} ${targetDir}/${snapshotOut} || {
        sysLog "Failed to create snapshot of ${sourceDir} in ${targetDir}" ; exit 1
    }

    sysLog "Snapshot of ${sourceDir} created in ${targetDir}"

}

function restoreSnapshot () {

    _restoreHelpInfo="$(cat << EOF
${_versionInfo}

Usage: ${_appName} restore <flags> arg...

Options:
    restore                   Restore a subvolume to a previous state.

Flags:
    -l, --list                List all available snapshots in the snapshot directory.
    -y, --yes                 Skip the confirmation prompt before restoring the snapshot.
    -s, --source <source>     Specify the source to be restored: [\`root\`, \`home\`, or \`logs\`].
    -h, --help                Show help information for restoring a snapshot.

${_licenseInfo}
EOF
)"

    shift

    local tmpDir fsPath snapshotsList targetDir

    # Get the dev path of the btrfs filesystem
    fsPath="$(lsblk -o fstype,path | awk '$1 == "btrfs" {print $2}')"

    case "${1}" in
        -h|--help                 ) echo "${_restoreHelpInfo}"                ; exit 0 ;;
    esac

    # Check if the script is run with root privileges
    rootRequired

    tmpDir="$(mktemp -d)"

    mount "$fsPath" "$tmpDir" || { sysLog "Failed to mount btrfs filesystem $fsPath" ; exit 1 ; }

    _snapshotsDir="$tmpDir/@snapshots"

    while true ; do case "${1}" in
        -l|--list                 )
            # List all available snapshots in the snapshot subvolume
            snapshotsList=() ; targetDir="$_snapshotsDir"
            while IFS= read -r -d $'\0' snap; do
                snapshotsName=$(basename "$snap") && snapshotsList+=("$snapshotsName")
            done < <(find "$targetDir" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

            test "${#snapshotsList[@]}" -eq 0 && { sysLog "No snapshots found in ${targetDir}" ; exit 1 ; }

            echo "Please select a snapshot to restore from: (ctrl+c to cancel)"
            echo ""

            select snap in "${snapshotsList[@]}" ; do
                test -z "${snap}" || { selectedSnapshot="$snap" ; break ; }
            done
            shift
        ;;
        -y|--yes                  ) confirm="yes"                             ; shift  ;;
        -s|--source               )
            # Set the source directory to restore
            case "${2}" in
                root                ) sourceDir="@";;
                home                ) sourceDir="@home";;
                logs                ) sourceDir="@log";;
                *                   ) sysLog "Invalid source directory: ${2}" ; exit 1 ;;
            esac
            shift 2
        ;;
        *) break ;;
    esac ; done

    if test "${confirm}" != "yes" ; then
        # Prompt for confirmation before restoring the snapshot
        read -rp "Are you sure you want to restore ${sourceDir} from ${selectedSnapshot}? [y/N] " choice
        case "${choice}" in
            [yY][eE][sS]|[yY]       ) ;;
            *                       ) sysLog "Snapshot restoration cancelled" ; exit 0 ;;
        esac
    fi

    # Delete source target
    btrfs su delete "${tmpDir}/${sourceDir}" || {
        sysLog "Failed to delete source directory ${tmpDir}/${sourceDir}" ; exit 1
    }

    # Restore the snapshot
    btrfs su snapshot "$tmpDir/@snapshots/${selectedSnapshot}" "${tmpDir}/${sourceDir}" || {
        sysLog "Failed to restore snapshot ${selectedSnapshot} to ${tmpDir}/${sourceDir}" ; exit 1
    }

    sysLog "Snapshot ${selectedSnapshot} restored to ${tmpDir}/${sourceDir}"

}

set -eo pipefail

# shellcheck disable=SC1091
source /etc/btrfs-snapshot.conf || {
    sysLog "Configuration file /etc/btrfs-snapshot.conf not found" ; exit 1
}

test ! -f /etc/os-release || source /etc/os-release

_appName="btrfs-snapshot"
_appVersion="$(cat /usr/share/doc/btrfs-snapshot/version || echo "unknown")"

# Default values for general snapshot for the root filesystem
_distroName="${DISTRO_NAME:-$NAME}"
_snapshotType="${SNAPSHOT_TYPE:-root}"

_snapshotsDir="${SNAPSHOT_DIR:-/.snapshots}"
_setDate="${SET_DATE:-true}"
_readOnly="${READ_ONLY:-false}"

# How many snapshots to keep. This should be keep low to avoid using too much disk space.
_totalCount="${TOTAL_COUNT:-7}"

_licenseInfo="$(cat << EOF
$_appName - Copyright (c) 2024 by Michael L. Schaecher <MichaelLeeSchaecher@gmail.com> under the terms
of the GPLv3 License or later.
EOF
)"

_versionInfo="$(cat << EOF
${_appName} [ version ${_appVersion} ] - ${_distroName}
EOF
)"

_helpInfo="$(cat << EOF
${_versionInfo}

Usage: ${_appName} [options] <flags> arg...

Options:
    create                      Create a new snapshot based on configured settings.
    delete                      Delete a snapshot based on configured settings
    restore                     Restore a subvolume to a previous state
    list                        List all snapshots in the snapshot directory.
    help                        Show this help message.
    version                     Show version information.

Flags:
    -h, --help                  Show help information for options: (\`create\`, \`delete\`, \`restore\`)

${_licenseInfo}
EOF
)"

trap "cleanUp" SIGINT

case "${1}" in
    create                  ) takeSnapshot "${@}"                                      ;;
    delete                  ) deleteSnapshotList "${@}"                                ;;
    restore                 ) restoreSnapshot "${@}"                                   ;;
    list                    )
        # List all snapshots in the snapshot directory
        if test -d "${_snapshotsDir}" ; then
            echo "Available snapshots in ${_snapshotsDir}:"
            echo ""

            find "${_snapshotsDir}" -mindepth 1 -maxdepth 1 -type d | sort | while read -r snap ; do
                echo "$(basename "${snap}")"
            done
        else
            echo "No snapshots found in ${_snapshotsDir}"
        fi
        exit 0
    ;;
    help                    ) echo "${_helpInfo}"                             ; exit 0 ;;
    version                 ) echo "${_versionInfo}"                          ; exit 0 ;;
    *                       ) echo "Invalid argument: ${1}"                   ; exit 1 ;;
esac

echo "done" ; exit 0
