#!/bin/env bash

# Pre remove script for dpkg/apt
case "${1}" in
    remove|purge|upgrade)
        if systemctl is-active --quiet btrfs-snapshot.timer ; then
            systemctl disable --now btrfs-snapshot.timer
            rm -f /usr/lib/systemd/system/btrfs-snapshot.timer
        fi

        if command -v btrfs-snapshots-manager &> /dev/null ; then
            apt purge --yes btrfs-snapshots-manager
        fi
    ;;
    *)
        echo "prerm called with unknown argument ${1}" >&2
        exit 0
    ;;
esac
