#!/bin/env bash

# Automatically added by dh_installinit
case "$1" in
    configure)
        # Older version placed the main script in /usr/sbin, newer versions in /usr/bin
        # remove the file if it exists in the old location
        if systemctl is-enabled --quiet btrfsnapd.timer ; then
            systemctl daemon-reload
        else
            systemctl enable --now btrfsnapd.timer
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
