#!/bin/sh

set -e

case "$1" in
	remove|purge									)
		systemctl disable --now btrfsnapd.service >/dev/null || true
		systemctl disable --now btrfsnapd.timer >/dev/null || true
	;;
	abort-upgrade|abort-deconfigure|abort-remove	) ;;
	*												)
		echo "Unsupported action: $1" ; exit 1
	;;
esac

exit 0
