#!/bin/sh

set -e

case "$1" in
	remove											)
		systemctl stop btrfsnapd.service >/dev/null || true
		systemctl stop btrfsnapd.timer >/dev/null || true
	;;
	purge											)
		systemctl disable --now btrfsnapd.* 2>/dev/null || true
	;;
	abort-upgrade|abort-deconfigure|abort-remove	) ;;
	*												)
		echo "Unsupported action: $1" ; exit 1
	;;
esac

exit 0
