#!/bin/env bash

set -e

test -z "${PACKAGE}" && echo "PACKAGE not set" && exit 1
test -z "${VERSION}" && echo "VERSION not set" && exit 1
test -z "${ARCH}" && echo "ARCH not set" && exit 1

if test -d "../../mls" && test ! -d "../../mls/pool/main/b/${PACKAGE}" ; then
	mkdir -vp "../../mls/pool/main/b/${PACKAGE}"
fi

if test -d "../../mls" ; then
    rm -vf ../../mls/pool/main/b/"${PACKAGE}"/*.deb
	dpkg-deb --root-owner-group --build "${PACKAGE_DIR}" \
		"../../mls/pool/main/b/${PACKAGE}/${PACKAGE}_${VERSION}_${ARCH}.deb"
else
	dpkg-deb --root-owner-group --build "${PACKAGE_DIR}" "${PACKAGE}_${VERSION}_${ARCH}.deb"
fi