#!/bin/env bash

set -eo pipefail

# shellcheck disable=SC1091
source /etc/os-release

# shellcheck disable=SC1091
source /etc/btrfs-snapshots-manager.conf

# Set the number of snapshots to keep

test "$(id -u)" -eq "0" || { echo "Must be root to run this script"; exit 1; }

test "false" = "${READONLY}" || SNAPSHOT_OPTIONS="-r"

btrfs su snapshot "${SNAPSHOT_OPTIONS}" / "${SNAPSHOT_PATH}" || { echo "Failed to create snapshot"; exit 1; }


# Delete snapshots exceeding the total to keep
# shellcheck disable=SC2012
while true ; do

    OLD_SNAPSHOTS="$(btrfs su list -o --sort=ogen "${SNAPSHOT_DIR}" | awk -F'/' 'NR==1 {print $2}')"

    if test "$(ls -1 "${SNAPSHOT_DIR}" | wc -l)" -gt "${TOTAL_KEEP}" ; then
        btrfs su delete "${SNAPSHOT_DIR}/${OLD_SNAPSHOTS}" || { echo "Failed to delete: ${OLD_SNAPSHOTS}" ; exit 1; }
    else
        break
    fi

done

# shellcheck disable=SC2012
echo "Total snapshots: $(ls -1 "${SNAPSHOT_DIR}" | wc -l)"

exit 0
