#!/bin/env bash

set -eo pipefail

source /etc/os-release

source /etc/btrfs-snapshots-manager.conf

# Set the number of snapshots to keep

test "$(id -u)" -eq 0 || { echo "Must be root to run this script"; exit 1; }

btrfs subvolume snapshot / "${SNAPSHOT_DIR}/${SNAPSHOT_PREFIX}" || { echo "Failed to create snapshot"; exit 1; }

echo "Total snapshots: $(ls -1 "${SNAPSHOT_DIR}" | wc -l)"

# Delete snapshots exceeding the total to keep
while [ "$(ls -1 "${SNAPSHOT_DIR}" | wc -l)" -gt "${TOTAL_KEEP}" ]; do

    OLD_SNAPSHOTS=$(ls -1 "${SNAPSHOT_DIR}" | sort -r | tail -n 1)

    btrfs subvolume delete "${SNAPSHOT_DIR}/${OLD_SNAPSHOTS}" || { echo "Failed to delete: ${OLD_SNAPSHOTS}"; exit 1; }

done

echo "Total snapshots: $(ls -1 "${SNAPSHOT_DIR}" | wc -l)"

exit 0
